config/routes.rb
Rails.application.routes.draw do
  resources :member_tasks
  root to: 'pages#status'

  resources :tasks
  resources :members

  get 'update_member_task/:id', to: 'tasks#update_member_task'
  patch 'update_member_task', to: 'tasks#assign_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true

  has_many :tasks, through: :member_tasks
  has_many :member_tasks
end

app/models/member_task.rb
class MemberTask < ApplicationRecord
  belongs_to :member
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :members, through: :member_tasks
  has_many :member_tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/member_tasks_controller.rb
class MemberTasksController < ApplicationController
  before_action :set_member_task, only: [:show, :edit, :update, :destroy]

  # GET /member_tasks
  # GET /member_tasks.json
  def index
    @member_tasks = MemberTask.all
  end

  # GET /member_tasks/1
  # GET /member_tasks/1.json
  def show
  end

  # GET /member_tasks/new
  def new
    @member_task = MemberTask.new
  end

  # GET /member_tasks/1/edit
  def edit
  end

  # POST /member_tasks
  # POST /member_tasks.json
  def create
    @member_task = MemberTask.new(member_task_params)

    respond_to do |format|
      if @member_task.save
        format.html { redirect_to @member_task, notice: 'Member task was successfully created.' }
        format.json { render :show, status: :created, location: @member_task }
      else
        format.html { render :new }
        format.json { render json: @member_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_tasks/1
  # PATCH/PUT /member_tasks/1.json
  def update
    respond_to do |format|
      if @member_task.update(member_task_params)
        format.html { redirect_to @member_task, notice: 'Member task was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_task }
      else
        format.html { render :edit }
        format.json { render json: @member_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_tasks/1
  # DELETE /member_tasks/1.json
  def destroy
    @member_task.destroy
    respond_to do |format|
      format.html { redirect_to member_tasks_url, notice: 'Member task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_task
      @member_task = MemberTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_task_params
      params.require(:member_task).permit(:member, :task, :task_type)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def status
    @assigned_tasks = MemberTask.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def update_member_task
    @member_task = MemberTask.find(params[:id])
  end

  def assign_task
    respond_to do |format|
      if @member_task.update(member_task_params)
        format.html { redirect_to root_path, notice: 'Member Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_task }
      else
        format.html { render :edit }
        format.json { render json: @member_task.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :location, :comment)
    end

    def member_task_params
      params.require(:task).permit(:member_id, :task_id, :task_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member_tasks_helper.rb
module MemberTasksHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/member_tasks/_form.html.erb
<%= simple_form_for(@member_task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :member %>
    <%= f.input :task %>
    <%= f.input :task_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/member_tasks/edit.html.erb
<h1>Editing Member Task</h1>

<%= render 'form', member_task: @member_task %>

<%= link_to 'Show', @member_task %> |
<%= link_to 'Back', member_tasks_path %>

app/views/member_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Member Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Member</th>
      <th>Task</th>
      <th>Task type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @member_tasks.each do |member_task| %>
      <tr>
        <td><%= member_task.member %></td>
        <td><%= member_task.task %></td>
        <td><%= member_task.task_type %></td>
        <td><%= link_to 'Show', member_task %></td>
        <td><%= link_to 'Edit', edit_member_task_path(member_task) %></td>
        <td><%= link_to 'Destroy', member_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member Task', new_member_task_path %>

app/views/member_tasks/new.html.erb
<h1>New Member Task</h1>

<%= render 'form', member_task: @member_task %>

<%= link_to 'Back', member_tasks_path %>

app/views/member_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @member_task.member %>
</p>

<p>
  <strong>Task:</strong>
  <%= @member_task.task %>
</p>

<p>
  <strong>Task type:</strong>
  <%= @member_task.task_type %>
</p>

<%= link_to 'Edit', edit_member_task_path(@member_task) %> |
<%= link_to 'Back', member_tasks_path %>

app/views/members/_form.html.erb
<%= form_for(member) do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/pages/status.html.erb
<h1>Pages#status</h1>
<p>Find me in app/views/pages/status.html.erb</p>

<ul>
<% @assigned_tasks.each do |t| %>
  <li><%= t.member.name %> is doing <%= t.task.name %></li>
<% end %>
</ul>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.location %></td>
        <td><%= task.comment %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @task.location %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @task.comment %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update_member_task.html.erb
<%= simple_form_for(@member_task, url: update_member_task_path, method: :patch) do |f| %>
  <% if @member_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_task.errors.count, "error") %> prohibited this @member_task from being saved:</h2>

      <ul>
      <% @member_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.association :member %>
  </div>

  <div class="field">
    <%= f.association :task %>
  </div>

  <div class="field">
    <%= f.input :task_type, collection: ["Current Task", "Next Task"] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>